using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CheckCars.Models
{
    /// <summary>
    /// Represents a photo associated with a report.
    /// </summary>
    public class Photo
    {
        /// <summary>
        /// Gets or sets the unique identifier for the photo.
        /// This value is not generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string PhotoId { get; set; } = Guid.NewGuid().ToString();

        /// <summary>
        /// Gets or sets the file name of the photo.
        /// </summary>
        public string? FileName { get; set; }

        /// <summary>
        /// Gets or sets the full file path of the photo.
        /// </summary>
        public string? FilePath { get; set; }

        /// <summary>
        /// Gets or sets the date when the photo was taken.
        /// </summary>
        public DateTime DateTaken { get; set; }

        /// <summary>
        /// Gets or sets the foreign key to the associated report.
        /// </summary>
        [ForeignKey("Report")]
        public string? ReportId { get; set; }

        /// <summary>
        /// Navigation property to the related report.
        /// </summary>
        public Report? Report { get; set; }
    }
}
